all: main.cpp polynom.h polynom.cpp block.h block.cpp lsx.h lsx.cpp pi.h pi.cpp l.h l.cpp key.h key.cpp kuznechik.h kuznechik.cpp
	g++ -Ofast -o kuznechik main.cpp polynom.cpp block.cpp lsx.cpp pi.cpp l.cpp key.cpp kuznechik.cpp -std=c++17 -g
